# Generated by Django 2.1.15 on 2022-02-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_activ4e',
            new_name='is_active',
        ),
    ]
